apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq
  namespace: kafka
data:
  application.yml: |
    akhq:
      server:
        access-log:
          enabled: false
          name: org.akhq.log.access
      connections:
          local:
            properties:
              bootstrap.servers: "my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc:9092"
