direct-runner:
	gradle run --args " \
	--candidateFile=./data/sponsored_search_orders_*.candidate.csv.gz \
	--baselineFile=./data/sponsored_search_orders_*.baseline.csv.gz \
	--outputFile=./data/sponsored_search_orders.csv.gz \
	"
