direct-runner:
	gradle run --args " \
	--inputFile=./data/sponsored_search_orders_2022-11-07.candidate.*.csv.gz \
	--baselineFile=./data/sponsored_search_orders_2022-11-07.baseline.*.csv.gz \
	--outputFile=./data/sponsored_search_orders_2022-11-07.deduped.csv.gz \
	"
